#$ -cwd
#$ -q node0
#$ -S /bin/bash

module load cutadapt/v1.10
## module load Fastqc/v0.11.4

limit=5
DATADIR=/../00_Data
DIRS=$DATADIR/Sample_*
mkdir -p $DATADIR/AdaptersRemoved

for D in $DIRS ##if D is a directory with name containing "Sample_" run cut adapt for all files ending with ".gz"
do
	for f in $D/*.fastq.gz
	do
    	cutadapt -u 15 -o $DATADIR/AdaptersRemoved/$f $f 
    done
    if [ $limit -eq 1 ]
    then
    	break
    fi
    let limit-=1
done


## fastqc ../00_Data/Sample_l100e1/TestAdaptersRemoved/NoPrimer3_l100e1_CCATAGCA-TAGATCGC_L001_R1_001.fastq.gz


