#$ -cwd
#$ -q node0
#$ -S /bin/bash

## Removing too short sequences using cutadapt
## Creates new directory for long sequences 
## where sequences that pass the filer are witten to new files

module load cutadapt/v1.10

DIR=../00_Data 						#Root of all data
cleanDIR=$DIR/cleaned				#Directory of files to be filtered
mkdir -p $DIR/longSeq		 		#Creating directory for new fastq files

##Looping over all files in directory of files to be checked
##Removing too short sequences and writing passing seq to new files 
for f in $cleanDIR/*.fastq.gz
do
	FILE=${f#$cleanDIR}
   	cutadapt -m 100 -o $DIR/longSeq/$FILE $f
done