#$ -cwd
#$ -q node0
#$ -S /bin/bash

## Script used for testing cutadapt on one fastq file
## Creates a new file for the cut sequence and runs fastqc analysis on the file

module load cutadapt/v1.10
module load Fastqc/v0.11.4

cutadapt -g NNNNCGGTAAYTCCAGCTCYV -o ../00_Data/Sample_l100e1/TestAdaptersRemoved/NoFPrim_l100e1_CCATAGCA-TAGATCGC_L001_R1_001.fastq.gz ../00_Data/Sample_l100e1/l100e1_CCATAGCA-TAGATCGC_L001_R1_001.fastq.gz

#Not working when removing this particular seqence, likely misinterpreting phredscore
fastqc ../00_Data/Sample_l100e1/TestAdaptersRemoved/NoFPrim_l100e1_CCATAGCA-TAGATCGC_L001_R1_001.fastq.gz
