#!/bin/bash
#$ -cwd
#$ -q node0
#$ -S /bin/bash

##For all directories with name containing "Sample_" in root data directory
##run cutadapt for all files ending with ".gz"
##Specifies what to cut depenting on if the file contains forward(R1) or reverse(R2) reads
##Set limit to max number of samples that should be processed

#module load cutadapt/v1.10
#module load Fastqc/v0.11.4

#limit=5
DATADIR=../00_Data #Root of all data
DIRS=$DATADIR/Sample_*				#All directories in which to look for data files
mkdir -p $DATADIR/AdaptersRemoved 		#Creating directory for new fastq files

for D in $DIRS 
do
	for f in $D/*.fastq.gz
	do
		FILE=${f#$D}         #Removing directory form file name 
		if [[ $FILE =~ R1 ]] #If file name contains R1
    	then
    		cutadapt -g NNNNCGGTAAYTCCAGCTCYV -o $DATADIR/AdaptersRemoved/$FILE $f    #Removing second half of primer 574*f 
    	elif [[ $FILE =~ R2 ]]
    	then
    		cutadapt -g CCGTCAATTHCTTYAART -o $DATADIR/AdaptersRemoved/$FILE $f       #Removing second half of primer 1132r
    	fi 
    done
#    if [ $limit -eq 1 ]     #if read enough samples, exit loop
#    then
#    	break
#    fi
#    let limit-=1            #increasing number of samples processed
done


## fastqc ../00_Data/Sample_l100e1/TestAdaptersRemoved/NoPrimer3_l100e1_CCATAGCA-TAGATCGC_L001_R1_001.fastq.gz


