#!/bin/bash
#$ -cwd
#$ -q node0
#$ -S /bin/bash

## Trimming fixed amount of bases from the right using cutadapt
## More is trimmed from R2 reads due to poorer mean quality
## Uses the dataset where primers have already been removed, creates new directory for trimmed files
## One of two method used for trimming the data. Less stringent than trimTails 

#module load cutadapt/v1.10

DIR=../00_Data 				#Root of all data
NoAdapDIR=$DIR/AdaptersRemoved		#Directory of files to be trimmed
mkdir -p $DIR/trim_cutadapt 		#Creating directory for new fastq files

##Looping over all files in directory of files to be trimmed
##Checking if file is R1 och R2 and cutting accordingly
##writes trimmed sequences to new files
for f in $NoAdapDIR/*.fastq.gz
do
	FILE=${f#$NoAdapDIR}
	if [[ $FILE =~ R1 ]]
   	then
   		cutadapt -u -20 -o $DIR/trim_cutadapt/$FILE $f
   	elif [[ $FILE =~ R2 ]]
   	then
   		cutadapt -u -90 -o $DIR/trim_cutadapt/$FILE $f
   	fi 
done
